name: Unit Tests
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Run Pytests
    env:
        SQL_QUEUE_NAMEt: est
        SQL_QUEUE_POSTGRES_HOSTNAME: localhost
        SQL_QUEUE_POSTGRES_USER: postgres
        SQL_QUEUE_POSTGRES_PASSWORD: postgres
        SQL_QUEUE_POSTGRES_DATABASE: postgres
        SQL_QUEUE_POSTGRES_PORT: 5432
    shell: bash