services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  minio: 
    image: quay.io/minio/minio:RELEASE.2024-04-28T17-53-50Z

    # to create a default `unit-tests` bucket 
    entrypoint: sh
    command: -c 'mkdir -p /data1/unit-tests && /usr/bin/minio server --console-address ":9001" /data1'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data1-1:/data1

volumes:
  db:
    driver: local
  data1-1:
