apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: queue-test-template
spec:
  entrypoint: run-a-test
  ttlStrategy:
    secondsAfterCompletion: 300
  templates:
  - inputs:
      parameters:
      - name: bin_file
      - name: force-fail
        value: False
      - name: run-time-sec
        value: 1
    name: run-a-test
    script:
      command:
      - python
      image: python:3.8
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        import json
        try: bin_file = json.loads(r'''{{inputs.parameters.bin_file}}''')
        except: bin_file = r'''{{inputs.parameters.bin_file}}'''

        if {{inputs.parameters.force-fail}}:
          exit(1)

        import time
        print(f'Parsing {bin_file}')
        time.sleep({{inputs.parameters.run-time-sec}})
        print(f'Parsed {bin_file}')
