name: Integration Tests
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Install minio
    run: |
      wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230518000536.0.0_amd64.deb -O minio.deb
      sudo dpkg -i minio.deb
  - name: Launch minio
    continue-on-error: true
    run: |
      mkdir ~/minio
      minio server ~/minio --console-address :9090 &!
  - name: Setup Minikube
    id: minikube
    uses: medyagh/setup-minikube@latest
  - name: Prepare for Argo Tests
    run: |
      minikube start
      kubectl create namespace pivot
      kubectl apply -n pivot -f resources/quick-start-minimal.yaml
      kubectl apply -n pivot -f resources/test_workflow_template.yaml
      kubectl wait -n pivot --timeout=300s --for=condition=Ready --all pods
      kubectl port-forward -n pivot service/argo-server 2746:2746 &
  - name: Run Pytests
    run: |
      export RUN_ARGO_TESTS=True
      export SQL_QUEUE_NAME=test
      export SQL_QUEUE_POSTGRES_HOSTNAME=localhost
      export SQL_QUEUE_POSTGRES_USER=postgres
      export SQL_QUEUE_POSTGRES_PASSWORD=postgres
      export SQL_QUEUE_POSTGRES_DATABASE=postgres
      export SQL_QUEUE_POSTGRES_PORT=5432
      export AWS_ACCESS_KEY_ID=minioadmin
      export AWS_SECRET_ACCESS_KEY=minioadmin
      export FSSPEC_S3_ENDPOINT_URL=http://172.17.0.1:9000/
      pytest -vv -m integration
  shell: bash
