name: publish
on: 
  workflow_dispatch:
  push:
jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build image
        run: |
          docker build . -t ghcr.io/afmc-majcom/task-queue/task-queue

      - name: test controller
        run: |
          docker run ghcr.io/afmc-majcom/task-queue/task-queue:latest controller --help
          
      - name: test server
        run: |
          docker run ghcr.io/afmc-majcom/task-queue/task-queue:latest server 
          docker ps
          
      - name: Login to ghcr.Io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #- name: publish image
        #run: |
          #docker push ghcr.io/afmc-majcom/task-queue/task-queue:latest
