name: publish
on:
  push:
    branches: [ "main" ]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ghcr.Io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker build . -t ghcr.io/afmc-majcom/task-queue/task-queue:latest
          docker run ghcr.io/afmc-majcom/task-queue/task-queue:latest controller --help 
          docker push ghcr.io/afmc-majcom/task-queue/task-queue:latest
