# This workflow will install Python dependencies, and run tests.

name: Task Queue CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
     uses: ./.github/workflows/build.yml
  testing:
    needs: build
    name: Run Tests
    runs-on: ubuntu-latest
    steps:    
      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:          
          testing: true

  linting:
    name: Lint Code
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Ruff
        uses: actions/checkout@v4
      - name: ruff
        uses: chartboost/ruff-action@v1
