
name: Task Queue Manual Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
   validate_code:
     name: Validate Code if Not on Main
     if: github.ref != 'refs/heads/main'
     uses: ./.github/workflows/validate_code.yml

   publish-docker-image:
     needs: [validate_code]
     permissions:
       packages: write
     uses: ./.github/workflows/publish_docker_image.yml
