
name: Task Queue Manual Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
   validate:
     name: validate
     if: github.ref != 'refs/heads/main'
     uses: ./.github/workflows/validate_code.yml

   publish-docker-image:
     needs: [validate]
     permissions:
       packages: write
     uses: ./.github/workflows/publish_docker_image.yml
     with:
       name: _manual