
name: Task Queue Manual Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
   publish-docker-image:
     if: github.ref == 'refs/heads/main'
     permissions:
       packages: write
     uses: ./.github/workflows/publish_docker_image.yml
