
name: Task Queue Manual Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
   setup:
     runs-on: ubuntu-latest
     if: github.ref != 'refs/heads/main'
     steps:
     - uses: ./.github/workflows/validate_code.yml

   publish-docker-image:
     needs: [setup]
     runs-on: ubuntu-latest
     permissions:
       packages: write
     steps:
     - uses: ./.github/workflows/publish_docker_image.yml

