
name: Task Queue Manual Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
   validate:
    uses: ./.github/workflows/validate_code.yml

   publish-docker-image:
     needs: [validate]
     permissions:
       packages: write
     uses: ./.github/workflows/publish_docker_image.yml
