name: Python Unit Test

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

permissions:
  contents: read

env:
  ACTION_PATH: ${{ inputs.path }}

jobs:
  unit-test:
      runs-on: ubuntu-latest
      # env:
      #  ACTION_PATH: ${{ inputs.path }}
      steps:
      - uses: actions/checkout@v3
      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.10"
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pytest
      #     pip install .
      - name: Check Inputs
        run: echo ${{ env.ACTION_PATH }}
      - name: Run
        uses: ${{ env.ACTION_PATH }}@OPAL-668v2
      #   uses: ./.github/actions/unit-test
        # uses: AFMC-MAJCOM/task-queue/.github/actions/unit-test@OPAL-668v2
