name: Python Unit Test

on:
  workflow_call:
    inputs:
      owner:
        required: true
        type: string

permissions:
  contents: read

jobs:
  unit-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Check Inputs
        run: |
          echo ${{ job.inputs.owner }}
          echo ${{ github.event.inputs.owner }}
          echo ${{ jobs.inputs.owner }}
          echo ${{ steps.inputs.owner }}
      # - name: Run
      #   uses: ${{job.inputs.owner }}/task-queue/.github/actions/unit-test@OPAL-668v2
