# This workflow will run all pytests based on their marking.

name: Python Unit Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-test:
    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
        export SQL_QUEUE_NAME=test
        export SQL_QUEUE_POSTGRES_HOSTNAME=localhost
        export SQL_QUEUE_POSTGRES_USER=postgres
        export SQL_QUEUE_POSTGRES_PASSWORD=postgres
        export SQL_QUEUE_POSTGRES_DATABASE=postgres
        export SQL_QUEUE_POSTGRES_PORT=5432
        pytest -vv -m unit
