name: Python Unit Test

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  unit-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Check Inputs
        run: echo "ACTION_PATH=${{ inputs.path }}" >> $GITHUB_ENV
      # - name: Run
      #   uses: ${ACTION_PATH}
        # uses: ${{ inputs.owner }}/task-queue/.github/actions/unit-test@OPAL-668v2
