
on:
  workflow_call:

permissions:
  contents: read

jobs:
  generic-workflow:
    uses: AFMC-MAJCOM/ci_python/.github/workflows/ci.yaml@main
    with:
      project_root: task_queue

  unmarked-test:
    uses: AFMC-MAJCOM/ci_python/.github/workflows/unmarked_tests.yaml@OPAL-756 #dont merge until this is switched to main
    with:
      mark-inputs: not unit and not integration and not end2end

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run pytest setup
      uses: AFMC-MAJCOM/ci_python/.github/actions/pytest-setup@main
    - name: Run unit tests
      uses: ./.github/actions/unit-test

  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Run pytest setup
      uses: AFMC-MAJCOM/ci_python/.github/actions/pytest-setup@main
    - name: Run integration tests
      uses: ./.github/actions/integration-test

  # end2end not yet implemented in this repo
  # end2end-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Run pytest setup
  #     uses: AFMC-MAJCOM/ci_python/.github/actions/pytest-setup@main
  #   - name: Run integration tests
  #     uses: ./.github/actions/end2end-test
