
on:
  workflow_call:

permissions:
  contents: read

jobs:
  generic-workflow:
    uses: AFMC-MAJCOM/ci_python/.github/workflows/ci.yaml@main
    with:
      project_root: task_queue

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run pytest setup
      uses: AFMC-MAJCOM/ci_python/.github/actions/pytest-setup
    - name: Run unit tests
      uses: ./.github/actions/unit-test

  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run pytest setup
      uses: AFMC-MAJCOM/ci_python/.github/actions/pytest-setup
    - name: Run integration tests
      uses: ./.github/actions/integration-test

  end2end-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run pytest setup
      uses: AFMC-MAJCOM/ci_python/.github/actions/pytest-setup
    - name: Run integration tests
      uses: ./.github/actions/end2end-test
